name: flutter_live_shopping
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  http: ^1.2.2
  video_player: ^2.10.1
  equatable: ^2.0.7
  go_router: ^16.2.4
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.7.1
  json_serializable: ^6.8.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

flutter:
  uses-material-design: true
